# Generated by Django 4.1.7 on 2023-03-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='exerpt',
            new_name='excerpt',
        ),
    ]
